<?php

namespace src;
use src\Retangulo ;

class Quadrado extends Retangulo
{


    public function setLargura($largura)
    {
        parent::setAltura($largura); // TODO: Change the autogenerated stub
        parent::setLargura($largura);
    }

    public function setAltura($altura)
    {
        parent::setAltura($altura); // TODO: Change the autogenerated stub
        parent::setLargura($altura);
    }
}